config/routes.rb
Rails.application.routes.draw do
  root 'manifests#index'

  get 'iiif/:identifier/manifest' => 'manifests#serve'

  resources :manifests
  resources :sequences
  resources :canvases
  resources :images
  resources :resources

  get 'import/manifest' => 'import#manifest'
  post 'import/manifest/update' => 'import#manifest_update'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :a_id %><br>
    <%= f.text_field :a_id %>
  </div>
  <div class="field">
    <%= f.label :a_type %><br>
    <%= f.text_field :a_type %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th>A</th>
      <th>A type</th>
      <th>Format</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.a_id %></td>
        <td><%= resource.a_type %></td>
        <td><%= resource.format %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>A:</strong>
  <%= @resource.a_id %>
</p>

<p>
  <strong>A type:</strong>
  <%= @resource.a_type %>
</p>

<p>
  <strong>Format:</strong>
  <%= @resource.format %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>