config/routes.rb
Rails.application.routes.draw do
  root 'manifests#index'

  get 'iiif/:identifier/manifest' => 'manifests#serve'

  resources :manifests
  resources :sequences
  resources :canvases
  resources :images
  resources :resources

  get 'import/manifest' => 'import#manifest'
  post 'import/manifest/update' => 'import#manifest_update'

end

app/controllers/canvases_controller.rb
class CanvasesController < ApplicationController
  before_action :set_canvas, only: [:show, :edit, :update, :destroy]

  # GET /canvases
  # GET /canvases.json
  def index
    @canvases = Canvas.all
  end

  # GET /canvases/1
  # GET /canvases/1.json
  def show
  end

  # GET /canvases/new
  def new
    @canvas = Canvas.new
  end

  # GET /canvases/1/edit
  def edit
  end

  # POST /canvases
  # POST /canvases.json
  def create
    @canvas = Canvas.new(canvas_params)

    respond_to do |format|
      if @canvas.save
        format.html { redirect_to @canvas, notice: 'Canvas was successfully created.' }
        format.json { render :show, status: :created, location: @canvas }
      else
        format.html { render :new }
        format.json { render json: @canvas.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /canvases/1
  # PATCH/PUT /canvases/1.json
  def update
    respond_to do |format|
      if @canvas.update(canvas_params)
        format.html { redirect_to @canvas, notice: 'Canvas was successfully updated.' }
        format.json { render :show, status: :ok, location: @canvas }
      else
        format.html { render :edit }
        format.json { render json: @canvas.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canvases/1
  # DELETE /canvases/1.json
  def destroy
    @canvas.destroy
    respond_to do |format|
      format.html { redirect_to canvases_url, notice: 'Canvas was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_canvas
      @canvas = Canvas.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def canvas_params
      params[:canvas]
    end
end

app/helpers/canvases_helper.rb
module CanvasesHelper
end

app/views/canvases/_form.html.erb
<%= form_for(@canvas) do |f| %>
  <% if @canvas.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canvas.errors.count, "error") %> prohibited this canvas from being saved:</h2>

      <ul>
      <% @canvas.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/canvases/edit.html.erb
<h1>Editing Canvas</h1>

<%= render 'form' %>

<%= link_to 'Show', @canvas %> |
<%= link_to 'Back', canvases_path %>

app/views/canvases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Canvases</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @canvases.each do |canvas| %>
      <tr>
        <td><%= link_to 'Show', canvas %></td>
        <td><%= link_to 'Edit', edit_canvas_path(canvas) %></td>
        <td><%= link_to 'Destroy', canvas, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Canvas', new_canvas_path %>

app/views/canvases/new.html.erb
<h1>New Canvas</h1>

<%= render 'form' %>

<%= link_to 'Back', canvases_path %>

app/views/canvases/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_canvas_path(@canvas) %> |
<%= link_to 'Back', canvases_path %>