config/routes.rb
Rails.application.routes.draw do
  root 'manifests#index'

  get 'iiif/:identifier/manifest' => 'manifests#serve'

  resources :manifests
  resources :sequences
  resources :canvases
  resources :images
  resources :resources

  get 'import/manifest' => 'import#manifest'
  post 'import/manifest/update' => 'import#manifest_update'

end

app/models/sequence.rb
class Sequence
  include Mongoid::Document

  @@default_type = 'sc:Sequence'

  include Mongoid::Document

  field :@id, type: String
  field :@type, type: String, default: @@default_type
  field :label, type: String
  field :viewingDirection, type: String
  field :viewingHint, type: String

  embedded_in :manifests
  has_many :canvases

  def serializable_hash(options={})
    hash = super(options);
    hash[:canvases] = canvases.inject([]) do |acc, m|
      acc << m.serializable_hash
      acc
    end
    hash
  end

  def self.from_json_hash(obj)
    sequence = Sequence.new do |doc|
      doc['@id'] = obj['@id']
      doc['@type'] = obj['@type'] || @@default_type
      doc.label = obj['label']
      doc.viewingDirection = obj['viewingDirection'] if obj['viewingDirection']
      doc.viewingHint = obj['viewingHint'] if obj['viewingHint']
    end
    sequence
  end
end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  before_action :set_sequence, only: [:show, :edit, :update, :destroy]

  # GET /sequences
  # GET /sequences.json
  def index
    @sequences = Sequence.all
  end

  # GET /sequences/1
  # GET /sequences/1.json
  def show
  end

  # GET /sequences/new
  def new
    @sequence = Sequence.new
  end

  # GET /sequences/1/edit
  def edit
  end

  # POST /sequences
  # POST /sequences.json
  def create
    @sequence = Sequence.new(sequence_params)

    respond_to do |format|
      if @sequence.save
        format.html { redirect_to @sequence, notice: 'Sequence was successfully created.' }
        format.json { render :show, status: :created, location: @sequence }
      else
        format.html { render :new }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sequences/1
  # PATCH/PUT /sequences/1.json
  def update
    respond_to do |format|
      if @sequence.update(sequence_params)
        format.html { redirect_to @sequence, notice: 'Sequence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sequence }
      else
        format.html { render :edit }
        format.json { render json: @sequence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sequences/1
  # DELETE /sequences/1.json
  def destroy
    @sequence.destroy
    respond_to do |format|
      format.html { redirect_to sequences_url, notice: 'Sequence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sequence
      @sequence = Sequence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sequence_params
      params[:sequence]
    end
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/views/sequences/_form.html.erb
<%= form_for(@sequence) do |f| %>
  <% if @sequence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sequence.errors.count, "error") %> prohibited this sequence from being saved:</h2>

      <ul>
      <% @sequence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sequences/edit.html.erb
<h1>Editing Sequence</h1>

<%= render 'form' %>

<%= link_to 'Show', @sequence %> |
<%= link_to 'Back', sequences_path %>

app/views/sequences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sequences</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sequences.each do |sequence| %>
      <tr>
        <td><%= link_to 'Show', sequence %></td>
        <td><%= link_to 'Edit', edit_sequence_path(sequence) %></td>
        <td><%= link_to 'Destroy', sequence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sequence', new_sequence_path %>

app/views/sequences/new.html.erb
<h1>New Sequence</h1>

<%= render 'form' %>

<%= link_to 'Back', sequences_path %>

app/views/sequences/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sequence_path(@sequence) %> |
<%= link_to 'Back', sequences_path %>